### PR TITLE
🐛 Rename the GH Actions file for testing workstatus

### PR DESCRIPTION
**Pull request by waltforme**
## Summary
Forgot to rename the file in #28.

/cc @MikeSpreitzer

### CODE REVIEW

**Comment by ezrasilvera** [comment]
Why not call the workflow e2e ?  There are many projects that use a single workflow to trigger all e2e tests. 
In the future you may add additional tests not related to "operations"

**Comment by waltforme** [comment]
> Why not call the workflow e2e ? There are many projects that use a single workflow to trigger all e2e tests. In the future you may add additional tests not related to "operations"

Done.

**Comment by ezrasilvera** [comment]
Sorry to nag :-)   I meant test-e2e.yaml

**Comment by waltforme** [comment]
> Sorry to nag :-) I meant test-e2e.yaml

Sure. Done.

**Review by ezrasilvera — APPROVED** [review]

**Pull request merged**
