### PR TITLE
✨ Upgrade kube dependency to release 1.28.2

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR bumps the Kubernetes release that this repo depends on from 1.26.7 to 1.28.2 (which matches the ks/ks repo).
The 1.26 release is out of maintenance (see https://endoflife.date/kubernetes). It would probably be problematic to advance this further than ks/ks.

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by pdettori — COMMENTED** [review]
looks fine, but can you please check why CI tests are failing ?

**Comment by MikeSpreitzer** [comment]
The force-push to 3a169da upgrades the Go version (from 1.19 to 1.20) in `github/workflows/ci.yaml`.

**Comment by MikeSpreitzer** [comment]
And the force-push to a87c0b8 updates the Go version in the goreleaser workflow.

**Comment by MikeSpreitzer** [comment]
@pdettori: this is ready for another look.

**Review by pdettori — APPROVED** [review]
/lgtm

**Pull request merged**
